<xs:schema
        xmlns="urn:HAML.Namespace"
        xmlns:hamlns="urn:HAML.Namespace"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
        vc:minVersion="1.1"
        elementFormDefault="qualified" attributeFormDefault="unqualified"
        targetNamespace="urn:HAML.Namespace"
        version="0.6.1">
    <!---->

    <!-- HAML -->
    <xs:element name="haml">
        <xs:annotation><xs:documentation>
            This is the document root. It contains information identifying the document and reporting center..
            It serves as a root for a number of patients.

            Elements:
            ----------
            - haml-id: A structure containing an identifier of this document.
            - reporting-center: Freeform text field used to describe the reporting center who submitted this document.
            - patient: An element containing information about a patient, and which assays were applied to this patient.
            - requisition-reason: A freeform text field describing the use/purpose of this haml document.
                For example, the document may be intended for use in screening for solid organ transplant,
                stem cell transplant, or a platelet transfusion.
                You may also specify if this is used for scientific study or a clinical setting.

            Attributes:
            -----------
            version: Must be '0.6.1' to use this version of the HAML schema.
        </xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:all>
                <xs:element name="haml-id" type="hamlns:hamlid" minOccurs="0" maxOccurs="1"/>
                <xs:element type="xs:string" name="reporting-center" minOccurs="0" maxOccurs="1"/>
                <xs:element name="requisition-reason" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="patient" type="hamlns:patient" minOccurs="0" maxOccurs="unbounded"/>
            </xs:all>
            <xs:attribute name="version" use="required" fixed="0.6.1"/>
        </xs:complexType>
    </xs:element>

    <!-- HAMLID -->
    <xs:complexType name="hamlid">
        <xs:annotation><xs:documentation>
            Specifies a unique identifier for this HAML document.  This id follows
            the HL7 standard for uniqueness using a two-part key.  'root' is the
            unique organization identifier publicly registered for your organization.
            'extension' is the unique document id managed internally for your
            organization, but must be unique and identify this specific HML document.
            Together root and extension guarantee global uniqueness.

            http://www.oid-info.com/faq.htm
            http://www.hl7.org/oid/index.cfm

            Attributes:
            -----------
            - root:  Unique publicly registered identifier for the HAML
                creator's organization.
                (ex: NMDP HL7 id is "2.16.840.1.113883.3.1470")
                Format is expected to be a string of digits and dot
                delimiters.  (required)
            - extension:   A unique document identifier managed internally by the
                organization specified in 'root'. Can be any alphanumeric
                format desired by the organization. (ex: "haml-0.9.7-123456789.23a")
                (optional and must be at least 1 non-whitespace character
                long)
                NOTE - If extension is NOT included, the unique document
                identifier is expected to be appended at the end of the root
                identifier above in accordance with HL7 practices.
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element type="hamlns:root" name="root" minOccurs="0" maxOccurs="1"/>
            <xs:element type="hamlns:extension" name="extension" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <!-- HAMLID : ROOT -->
    <xs:simpleType name="root">
        <xs:annotation><xs:documentation>
            Unique publicly registered identifier for the HAML creator's organization.
            This can be an HL7 compliant field (ex: NMDP is "2.16.840.1.113883.3.1470")
            The format can also be a UUID like "5177ec14-495b-4fea-a8fc-de1311f241cd".
            Format is expected to be a string of digits and dot or hyphen delimiters.
        </xs:documentation></xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9a-zA-Z\.\-])+" />
        </xs:restriction>
    </xs:simpleType>

    <!-- HAMLID : EXTENSION -->
    <xs:simpleType name="extension">
        <xs:annotation><xs:documentation>
            A unique document identifier managed internally by the
            organization specified in 'root'. Can be any alphanumeric
            format desired by the organization. (ex: "haml-0.9.7-123456789.23a")
            (not required but must be at least 1 non-whitespace character long and
            guarantee uniqueness) -> if compliant to FHIR, this is required
        </xs:documentation></xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

    <!-- PATIENT -->
    <xs:complexType name="patient">
        <xs:annotation><xs:documentation>
            A patient from which the sample is drawn. The patient has a corresponding ID, and a number of samples

            Elements:
            ----------
            - patient-id: A freeform string which uniquely identifies a patient within this document
            - sample: This represents a serum sample drawn from this patient
            - diagnostic-report: Structure for reporting test results for the regulatory bodies / societies
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element type="xs:string" name="patient-id" minOccurs="1" maxOccurs="1" />
            <xs:element type="hamlns:sample" name="sample" minOccurs="0" maxOccurs="unbounded" />
            <xs:element type="hamlns:diagnostic-report" name="diagnostic-report" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!-- DIAGNOSTIC-REPORT -->
    <xs:complexType name="diagnostic-report">
        <xs:annotation><xs:documentation>
            This structures is intended to represent a superset of the requirements of common regulatory, standards,
            or accreditation bodies or their representatives. For example, EFI, ASHI, NMDP, ISO

            https://cdn.ymaws.com/www.ashi-hla.org/resource/resmgr/docs/standards/2025/2025_ashi_standards.pdf
            https://efi-web.org/uploads/files/EFI-Committees-Standard-Committee-Standards-v8.1.pdf
            https://cdn.ymaws.com/www.ashi-hla.org/resource/resmgr/docs/operations_manual/2026/final_-_2026_ashi_operations.pdf

            This structure It aims to specify the details of the approval of a report by a body, including the
            authorities involved in signing, interpreting, and performing an assay.

            This structure also contains a final antibody profile for a given patient.

            Elements:
            -----------
            - report-id: unique identifier for this specific diagnostic report.
                A standards body may require that a report has a unique identifying identifier.
            - report-date: The date on which the report was generated
            - transplant-source-id: An identifier of a transplant source within the namespace of an
                authority system. For example, a Eurotransplant donor id.
            - tissue-type: The type of tissue being analyzed in this report. For example, kidney.
            - patient-antibody-profile: A structure specifying the antibody profile as determined in assays performed
                and reported in this document
            - accreditation-institution: Name or ID of an accreditation institution
            - signing-authority: Exactly one signing authority is to be provided for the document. This individual
                is authoritative on signing this document.
            - results-interpreters: A structure containing individuals responsible for interpreting the results
                of assays within this document.
            - performers: A structure containing individuals responsible for performing the assays within this document.
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="report-id" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="report-date" type="hamlns:date" minOccurs="0" maxOccurs="1" />
            <xs:element name="transplant-source-id" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="tissue-type" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="patient-antibody-profile" type="hamlns:patient-antibody-profile" minOccurs="0" maxOccurs="1" />
            <xs:element name="accreditation-institution" type="hamlns:accreditation-institution" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="signing-authority" type="hamlns:signing-authority" minOccurs="0" maxOccurs="1" />
            <xs:element name="clinical-lab-director" type="hamlns:clinical-lab-director" minOccurs="0" maxOccurs="1" />
            <xs:element name="performer" type="hamlns:performer" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="results-interpreter" type="hamlns:results-interpreter" minOccurs="0" maxOccurs="unbounded" />
        </xs:all>
    </xs:complexType>

    <!-- ACCREDITATION-INSTITUTION -->
    <xs:complexType name="accreditation-institution">
        <xs:annotation><xs:documentation>
            This structure specifies info about the accreditation institution. This may be an international society,
            such as ASHI or EFI

            Elements:
            -----------
            - accreditation-body: The name of the body or organization responsible for accrediting this document.
            - accreditation-number: A number specific to the individual who performed accreditation, within the
                accreditation body namespace
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="accreditation-body" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="accreditation-number" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!-- SIGNING-AUTHORITY -->
    <xs:complexType name="signing-authority">
        <xs:annotation><xs:documentation>
            This describes the details and role of the authority responsible for signing the document

            Elements:
            -----------
            - signing-authority-id: An optional ID specifying a signing authority
            - signing-authority-name: The name of the individual who acts as a signing authority
            - institution: The institute who is being represented by the signing authority
            - address: The address of the institution of the signing authority.
            - role: The role assumed by the signing authority
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="signing-authority-id" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="signing-authority-name" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="institution" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="address" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="role" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!-- CLINICAL-LAB-DIRECTOR -->
    <xs:complexType name="clinical-lab-director">
        <xs:annotation><xs:documentation>
            This describes the details and role of the laboratory director who oversaw the assay performance and
            interpretation.

            Elements:
            -----------
            - lab-director-id: An optional ID specifying a lab director
            - lab-director-name: The name of the lab director
            - institution: The institute who is being represented by the lab director
            - address: The address of the institution of the lab director.
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="lab-director-id" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="lab-director-name" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="institution" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="address" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!-- RESULTS-INTERPRETER -->
    <xs:complexType name="results-interpreter">
        <xs:annotation><xs:documentation>
            This represents an individual who interpreted the results of an assay(s)

            Elements:
            -----------
            - interpreter-id: Unique identifier for this results-interpreter within the institution's namespace
            - assay-id: A reference to the assay(s) within this document which were interpreted by this individual
            - interpreter-type: The type of the interpreter.
                Perhaps a Technician or Medical Immunologist
            - interpreter-name: The first and last name of the interpreter.
            - institution: The institution or employer which is represented by the performer.
            - role: The role of the interpreter. This is the name of their position within the interpreting laboratory.
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="interpreter-id" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="assay-id" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="interpreter-type" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="interpreter-name" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="institution" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="role" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!-- PERFORMER -->
    <xs:complexType name="performer">
        <xs:annotation><xs:documentation>
            This represents an individual who was responsible for performing(carrying out) the test or assay

            Elements:
            -----------
            - performer-id: Unique identifier for this performer within the institution's namespace
            - assay-id: A reference to the assay(s) within this document which were performed by this individual
            - performer-type: The role or type of the performer.
                Perhaps a Technician or Medical Immunologist or Lab Director
            - performer-name: The first and last name of the performer.
            - institution: The institution or employer which is represented by the performer.
            - role: The role of the performer. This is the name of their position within the interpreting laboratory.
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="performer-id" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="assay-id" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="performer-type" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="performer-name" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="institution" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="role" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!-- PATIENT-ANTIBODY-PROFILE -->
    <xs:complexType name="patient-antibody-profile">
        <xs:annotation><xs:documentation>
            Interpretation of the antibody profile.
            This interpretation could result from a single assay or a combination of multiple assays.

            Elements:
            -----------
            - patient-antibody-date: Date when the profile was generated
            - interpretation-context: The clinical context wherein the profile was generated,
                for example "Kidney Transplantation Workup"
            - interpretation-context-comment: More details regarding the interpretation context
            - specificities: A collection of the antigenic specificities as determined by the assays
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="patient-antibody-date" type="hamlns:date" minOccurs="0" maxOccurs="1" />
            <xs:element name="interpretation-context" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="interpretation-context-comment" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="specificities" type="hamlns:specificities" minOccurs="0" maxOccurs="unbounded" />
        </xs:all>
    </xs:complexType>

    <!-- SPECIFICITIES -->
    <xs:complexType name="specificities">
        <xs:annotation><xs:documentation>
            A certain set of specificities, possibly positive or negative or acceptable.

            Elements:
            -----------
            - specificities-date: Date when the specificities were assigned
            - specificities-type: Valid options include "Positive", "Negative", "Acceptable", "Unacceptable"
            - specificities-string: PL string specifying the antigenic targets.
            - description: Extra context or notes describing the reason for assigning these specificities.
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="specificities-date" type="hamlns:date" minOccurs="0" maxOccurs="1" />
            <xs:element name="specificities-type" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="specificities-string" type="hamlns:hla-plstring" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!-- SAMPLE -->
    <xs:complexType name="sample">
        <xs:annotation><xs:documentation>
            This represents a sample, most likely of blood, which was drawn from a patient. The details of the sample
            and surrounding metadata can be specified here. The working sample is used to specify modifications and
            assays performed on this sample.

            Elements:
            -----------
            - sample-id: A string with a unique identifier for this sample
            - sample-datetime: A dateTime which identifies the date and (optionally) the time when a sample was drawn.
            - sample-type: Free-form text, usually this should be "Serum"
            - testing-laboratory: A string with a unique identifier for the laboratory where this sample was drawn
            - working-sample: The working sample specifies treatments which were applied to the sample.
    </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="sample-id" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="sample-date" type="hamlns:date" minOccurs="0" maxOccurs="1" />
            <xs:element name="sample-type" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="testing-laboratory" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="working-sample" type="hamlns:working-sample" minOccurs="0" maxOccurs="unbounded" />
        </xs:all>
    </xs:complexType>

    <!-- DATE -->
    <xs:simpleType name="date">
        <xs:annotation><xs:documentation>
            hamlns:date is a union of xs:dateTime and xs:date
            This allows including either a date or a dateTime data.

            Standard ISO Date formats are required.
        </xs:documentation></xs:annotation>
        <xs:union memberTypes="xs:dateTime xs:date"/>
    </xs:simpleType>

    <!-- TREATMENT -->
    <xs:complexType name="treatment">
        <xs:annotation><xs:documentation>
            A treatment describes a process which was performed on a working sample in preparation for
            solid phase analysis.
            A working sample may be e.g. diluted in preparation for solid-phase-panel analysis.

            Elements:
            -----------
            - method: A freeform description of the treatment which has been applied
            - method-description: Details on the method performed
            - dilution-factor: Denominator of the dilution ratio, e.g. "16" in the case of a 1:16 dilution
            - diluent: Substance used for dilution or buffer, e.g. PBS
            - temperature: Temperature of the treatment in Celsius
            - time-seconds: How long the treatment is performed.
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element type="xs:string" name="method"/>
            <xs:element type="xs:string" name="method-description" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:int" name="dilution-factor" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="diluent" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:float" name="temperature" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:float" name="time-seconds" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <!-- WORKING-SAMPLE -->
    <xs:complexType name="working-sample">
        <xs:annotation><xs:documentation>
            Working serum which is to be applied to assay.

            This structure specifies the treatments applied to a sample, and subsequent assay.
            A working-Sample is a type of serum, which is the treated patient sample or specimen.

            Elements:
            -----------
            - working-sample-id: A string with a unique identifier for this serum. Must be unique within this document
            - sample-date: A dateTime which identifies the date and (optionally) the time when a sample treatment was performed
            - testing-laboratory: A string with a unique identifier for the laboratory where this sample treatment was performed
            - treatment: A sequential list of treatments applied to the patient sample
            - assay: Details of the solid phase assay applied to this serum
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="working-sample-id" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="treatment-date" type="hamlns:date" minOccurs="0" maxOccurs="1" />
            <xs:element name="testing-laboratory" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="treatment" type="hamlns:treatment" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="assay" type="hamlns:assay" minOccurs="0" maxOccurs="unbounded" />
        </xs:all>
    </xs:complexType>

    <!-- ASSAY -->
    <xs:complexType name="assay">
        <xs:annotation><xs:documentation>
            An assay describes analysis of a sample. This is often a solid-phase assay, but may
            be a cell assay.

            Elements:
            -----------
            - assay-id: A unique identifier for this specific assay element. IDs should not be re-used within this document,
                to allow them to be used for unambiguous referencing within this document.
            - run-id: A unique identifier for this run.
            - performer-id: A reference to the performer-id used within this document, referring to who performed the assay
            - assay-date: Date and time the assay was performed
            - assay-kit: Details to the assay kit which was used to perform the test
            - target-bead-observation: Results and interpretation from observations of a target bead.
            - target-cell-observation: Results and interpretation from observations of a target cell.
            - assay-interpretation: Overall interpretation of antigenic results of this assay, perhaps for clinical decision making
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="assay-id" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="run-id" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="performer-id" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="assay-date" type="hamlns:date" minOccurs="0" maxOccurs="1"/>
            <xs:element name="assay-kit" type="hamlns:assay-kit" minOccurs="0" maxOccurs="1"/>
            <xs:element name="target-bead-observation" type="hamlns:target-bead-observation" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="target-cell-observation" type="hamlns:target-cell-observation" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="assay-interpretation" type="hamlns:assay-interpretation" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <!-- ASSAY-KIT -->
    <xs:complexType name="assay-kit">
        <xs:annotation><xs:documentation>
            This section describes the kit used to perform an antibody assay. It specifies metadata
            about the assay kit, such as identifiers, assay type, manufacturer, and kit-specific attributes

            Elements:
            -----------
            - assay-type: Assay type Ex. Solid Phase Panel or CDC
            - assay-catalog: A structure containing details of the catalog used to perform the assay
            - detection-reagent-catalog: Identifier of the catalog used for detection reagents, this may be the same
                catalog identifier as used in the assay
            - protocol-variations: A description of variations from standard
                protocols as defined by the manufacturer.
            - interpretation-software: The software which was used for analysis of the solid-phase-panel results
            - interpretation-software-version: The version of the software which was used for analysis of the
                solid-phase-panel results
            - raw-MFI-divider: This numerical value is used for comparing multiple analysis machines.
                It may be that  devices systematically have biases on the same sample, or perhaps raw MFI reads
                which vary among versions of machines.
                This constant could be used to e.g. calibrate raw-MFI across multiple batches.
                If raw-MFI-divider is not provided, it should be assumed that the divider is 1.
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="assay-type" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="assay-catalog" type="hamlns:catalog" minOccurs="0" maxOccurs="1" />
            <xs:element name="detection-reagent-catalog" type="hamlns:catalog" minOccurs="0" maxOccurs="1" />
            <xs:element name="protocol-variations" type="hamlns:protocol-variations" minOccurs="0" maxOccurs="1" />
            <xs:element name="interpretation-software" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="interpretation-software-version" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element type="xs:double" name="raw-MFI-divider" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!-- CATALOG -->
    <xs:complexType name="catalog">
        <xs:annotation><xs:documentation>
            Details of the catalog used in an assay.
            This structure is used also to specify a catalog of detection reagents.

            Elements:
            ----------
            - kit-manufacturer: The company or institution which developed the kit
            - kit-description: Text description of assay kit, perhaps useful information about the loci targeted
                or specialization of the specific kit.
            - catalog-number: Identifier of the catalog, probably as provided by the manufacturer
            - lot-number: Identifier of the lot from within this catalog
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="kit-manufacturer" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="kit-description" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="catalog-number" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="lot-number" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!-- PROTOCOL-VARIATIONS -->
    <xs:complexType name="protocol-variations">
        <xs:annotation><xs:documentation>
            This structure contains information about modifications from standard protocols as defined by manufacturer,
            such as wash count, antiglobulin use, and serum treatment details, absorption.

            For example, you may need to specify a different detection technique on a standard assay, such as
            a C1q modification/ C3d modifications, or temperature variation, or a different number of serum washes
            performed.

            Elements:
            ----------
            - post-serum-wash-count: how many times the cells were washed after serum incubation
            - variation-type: A short definition of the type of variation which was applied to a protocol,
                when deviating from a standard vendor-specified protocol
			- variation-description:  A long description of the type of variation which was applied to a protocol,
                when deviating from a standard vendor-specified protocol
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="post-serum-wash-count" type="xs:int" minOccurs="0" maxOccurs="1" />
            <xs:element name="variation-type" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="variation-description" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!-- BEAD-INFO -->
    <xs:complexType name="bead-info">
        <xs:annotation><xs:documentation>
            This structure contains information about a bead within a panel.
            The bead likely has a certain HLA specificity or specificities, and it should be specified if this bead is
            a control bead or a test bead.

            Elements:
            ----------
            - bead-id: A string uniquely identifying this bead within the panel.
                For example, ID may be comprised of [assay-kit lot-number + bead-identifier]
            - bead-type: Valid options are "target", "positive-control", "negative-control"
            - HLA-target-type:  This is a PL String containing the HLA phenotype specificity of the bead.
                This is usually specifying a specific HLA molecule (2 fields of HLA nomenclature), or possibly multiple
                present molecules.
            - HLA-target-serological-specificity: This is an PL String containing the determined
                HLA serological specificity of the bead.
            - antigen-density: A numerical value specifying the absolute density of antigen present on this bead
            - relative-antigen-density: A numerical value specifying the relative density of antigen present on this
                bead. This may be used for comparison within this panel, and possibly for calculations of modified MFI.
           </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element type="xs:string" name="bead-id" minOccurs="1" maxOccurs="1" />
            <xs:element type="hamlns:bead-type" name="bead-type" minOccurs="1" maxOccurs="1" />
            <xs:element type="hamlns:hla-plstring" name="HLA-target-type" minOccurs="0" maxOccurs="1" />
            <xs:element type="hamlns:hla-plstring" name="HLA-target-serological-specificity" minOccurs="0" maxOccurs="1" />
            <xs:element type="xs:double" name="antigen-density" minOccurs="0" maxOccurs="1" />
            <xs:element type="xs:double" name="relative-antigen-density" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!-- BEAD-TYPE -->
    <xs:simpleType name="bead-type">
        <xs:annotation><xs:documentation>
            These are the types of beads present within a panel.
            A target bead is a bead with a specificity, where a positive or negative control bead
            may specify the presence or absence of antigens on a bead,
            intended to be used as a control for normalizing MFI values.
        </xs:documentation></xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="target"/>
            <xs:enumeration value="positive-control"/>
            <xs:enumeration value="negative-control"/>
            <xs:enumeration value="other"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- CELL-INFO -->
    <xs:complexType name="cell-info">
        <xs:annotation><xs:documentation>
            This structure contains information about a cell within a panel.
            The cell has a certain HLA specificity or specificities, and we can specify the intended use of the cell,
            as e.g. a positive or negative control.

            Elements:
            ----------
            - cell-id: A string uniquely identifying this cell within the panel.
                For example, ID may be comprised of [assay-kit lot-number + cell-identifier]
            - cell-type: Valid options are "target", "positive-control", "negative-control"
            - cell-source: A text description of the source or origin of the cells being observed.
            - HLA-target-type: This is a PL String containing the HLA phenotype specificity of the cell.
                This is usually specifying a specific HLA molecule (2 fields of HLA nomenclature), or possibly multiple
                present molecules.
            - HLA-target-serological-specificity: This is an PL String containing the determined
                HLA serological specificity of the cell.
            - antigen-density: A numerical value specifying the absolute density of antigen present on this cell
            - relative-antigen-density: A numerical value specifying the relative density of antigen present on this
                cell to be used for comparison within this panel, and possibly for calculations of modified MFI.

        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element type="xs:string" name="cell-id" minOccurs="1" maxOccurs="1" />
            <xs:element type="hamlns:bead-type" name="cell-type" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:string" name="cell-source" minOccurs="0" maxOccurs="1" />
            <xs:element type="hamlns:hla-plstring" name="HLA-target-type" minOccurs="0" maxOccurs="1" />
            <xs:element type="hamlns:hla-plstring" name="HLA-target-serological-specificity" minOccurs="0" maxOccurs="1" />
            <xs:element type="xs:double" name="antigen-density" minOccurs="0" maxOccurs="1" />
            <xs:element type="xs:double" name="relative-antigen-density" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!-- HLA-PLSTRING -->
    <xs:simpleType name="hla-plstring">
        <xs:annotation><xs:documentation>
            Syntactically valid Protein List using PL String based on plstring.org

            A PL String is a Phenotype List String. PL String encodes the HLA phenotype composition of reagents
            e.g. cells or single antigens used in antibody detection assays
            https://plstring.org/

            A PL String is often specified as HLA molecules, using standard HLA (two-field) nomenclature.
            A variety of serological typings can also be specified, depending on intended use case.
        </xs:documentation></xs:annotation>
        <xs:restriction base="xs:string">
        </xs:restriction>
    </xs:simpleType>

    <!-- BEAD-CLASSIFICATION -->
    <xs:simpleType name="classification">
        <xs:annotation><xs:documentation>
            This field describes if a bead or cell was determined as Positive or Negative.
            Borderline results are also allowed, which would indicate that this is a valid result,
            but is ambiguous if it should be called Positive or Negative. It could also be considered as Intermediate.

            Undetermined indicates an assessment could not be made, perhaps due to data quality issues.
        </xs:documentation></xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Positive"/>
            <xs:enumeration value="Negative"/>
            <xs:enumeration value="Questionable"/>
            <xs:enumeration value="Undetermined"/>
            <xs:enumeration value="Intermediate"/>
            <xs:enumeration value="Borderline"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- CDC-SCORE -->
    <xs:simpleType name="cdc-score">
        <xs:annotation><xs:documentation>
            This cdc scoring system is a numerical system for assigning the reactivity of a cell or bead, also known as a NIH
            classification.

            https://www.researchgate.net/figure/Score-system-for-the-analysis-of-the-standard-Complement-Dependent_tbl1_6949414

            It is originally based on an interpretation of the percent cytotoxicity observed.
            The NIH / Terasaki Score provides a specific categorizations applied to specific amounts of lost cells
            Score 1: 0% - 10% cell lysis (Negative)
            Score 2: 11% - 20% cell lysis (Doubtful/Weak)
            Score 4: 21% - 50% cell lysis (Weakly Positive)
            Score 6: 51% - 80% cell lysis (Positive)
            Score 8: >80% cell lysis (Strongly Positive)
                https://www.researchgate.net/figure/Score-system-for-the-analysis-of-the-standard-Complement-Dependent_tbl1_6949414

            This scoring system was historically carried over from cells to luminex assays,
            by using a mfi threshold instead of a cytotoxicity value.
        </xs:documentation></xs:annotation>
        <xs:restriction base="xs:int"/>
        <!--
        <xs:restriction base="xs:string">
            <xs:enumeration value="8"/>
            <xs:enumeration value="6"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="1"/>
            <xs:enumeration value="Undetermined"/>
        </xs:restriction>
        -->
    </xs:simpleType>

    <!-- BEAD-RAW-DATA -->
    <xs:complexType name="bead-raw-data">
        <xs:annotation><xs:documentation>
            Here we specify the raw data for a bead observation. This includes data as measured from the instrument,
            and should not specify modified, calculated, or normalized values.

            Elements:
            ----------
            - bead-count: Count of beads identified (int) for this observation (or bead gate)
            - raw-mfi: Raw MFI result for this bead and serum.
                Note: No modifications or calculations have been performed on this measurement.
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element type="xs:double" name="raw-MFI" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:double" name="bead-count" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <!-- CELL-RAW-DATA -->
    <xs:complexType name="cell-raw-data">
        <xs:annotation><xs:documentation>
            Here we specify the raw data for a cell observation. This includes data as measured from the instrument,
            and should not specify modified, calculated, or normalized values.

            Elements:
            ----------
            - raw-MFI: Raw MFI result for this cell and serum
                No modifications or calculations have been performed on this measurement.
            - raw-percent-cytotoxicity: Percentage of cells which died during an analysis
            - cell-count: How many cells were counted for this observation
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element type="xs:double" name="raw-MFI" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:double" name="raw-percent-cytotoxicity" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:double" name="cell-count" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <!-- ADJUSTED-DATA -->
    <xs:complexType name="adjusted-data">
        <xs:annotation><xs:documentation>
            Adjusted MFI results after formula and controls applied

            Elements:
            ----------
            - adjusted-data-id: ID, unique within this specific target-bead-observation/target-cell-observation
            - adjusted-mfi:  Adjusted result after formula and controls applied
            - formula: Declaration of formula applied to derive adjusted MFI or MFI ratio. Freeform text, for example:

                Modified MFI =
                (bead Raw - Sample Negative)
                - (Background raw - background negative)

                Modified MFI =
                (bead Raw / 3 - Sample Negative / 3)
                - (Background raw / 3 - background negative / 3)

				## e.g. background correction based upon the locus specific self background ###
				## for that I need to create A B C DRB1345, DQ DP adjustments -> 6 adjusted-data-IDs

				#1 for HLA-A
				Modified MFI =
                (bead Raw  - Self HLA-A background)

				#2 for HLA-B
				Modified MFI =
                (bead Raw  - Self HLA-B background)

				#3 for HLA-C
				Modified MFI =
                (bead Raw  - Self HLA-C background)

				Alternative
				#xx for self HLA locus-specific
				Modified MFI =
                (bead Raw  - Self HLA background related to the analyzed bead)

                This may also include information about the calibrator information.
            - plausible: Boolean indicator of bead or cell observation plausibility. If there is reason to indicate
                that this result is not plausible, this field can be set to "False" and details specified in
                "plausible-reason". If the field is not provided, plausible is assumed to be true.
            - plausible-reason: Reasoning declared for bead observation plausibility. For example, perhaps
                an instrument or preparation malfunction was observed.
                Another reason is that an antibody might target the transmembrane region of an HLA,
                and this is not a clinically relevant reactivity event.
                Or perhaps the antibody target is likely a self-antigen.

        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element type="xs:string" name="adjusted-data-id" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="adjustment-method" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:double" name="adjusted-mfi" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:double" name="mfi-ratio" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="formula" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:boolean" name="plausible" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="plausible-reason" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <!-- BEAD-INTERPRETATION -->
    <xs:complexType  name="bead-interpretation" >
        <xs:annotation><xs:documentation>
            This structure contains an interpretation of a single bead. It encapsulates the interpretation methods
            used and potentially a qualitative result summarizing the interpretation.

            Elements:
            ----------
            - adjusted-data-id: A reference to the adjusted-data-id which is used in this interpretation. This is useful
                if, for example, a MFI or Ratio threshold is applied. This id refers to the value was compared
                to the threshold.
            - bead-classification: A text Positive/Negative/Borderline/Unspecified classification.
            - bead-rank: a numerical rank specifying if there was reactivity on this bead.
            - mfi-threshold: Use this field to specify the numerical
                MFI threshold/cutoff which was used to classify a bead. (e.g. 500)
            - ratio-threshold: Use this field to specify the numerical
                MFI ratio threshold/cutoff which was used to classify a bead.
            - classification-entity: This is the individual, software, or entity
                which has performed a bead interpretation. For example, an analyst's name or position, or to clarify a
                human vs automated interpretation.
            - interpretation-reason: This is the reason or methodology for which a bead has been interpreted.
                For example, a standard MFI threshold (e.g. 500) was used
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element type="xs:double" name="adjusted-data-id" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="hamlns:classification" name="bead-classification" minOccurs="0" maxOccurs="1"/>
            <xs:element type="hamlns:cdc-score" name="bead-rank" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:double" name="mfi-threshold" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:double" name="ratio-threshold" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="classification-entity" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="interpretation-reason" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <!-- CELL-INTERPRETATION -->
    <xs:complexType  name="cell-interpretation" >
        <xs:annotation><xs:documentation>
            This structure contains an interpretation of a single cell.

            Elements:
            ----------
            - adjusted-data-id: A reference to the adjusted-data-id which is used in this interpretation. This is useful
                if, for example, a MFI or Ratio threshold is applied. This id refers to the value was compared
                to the threshold.
            - cell-classification: A text Positive/Negative/Borderline/Unspecified classification.
            - cdc-score: a numerical rank based on percentage of cytotoxicity
                specifying if there was reactivity on this well.
            - mfi-threshold: Use this field to specify the numerical
                MFI threshold/cutoff which was used to classify a cell. (e.g. 500)
            - ratio-threshold: Use this field to specify the numerical
                MFI ratio threshold/cutoff which was used to classify a cell.
            - classification-entity: This is the individual, software, or entity
                which has performed a cell interpretation. For example, an analyst's name or position, or to clarify a
                human vs automated interpretation.
            - interpretation-reason: This is the reason or methodology for which a cell has been interpreted.
                For example, a standard MFI threshold (e.g. 500) was used
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element type="xs:string" name="adjusted-data-id" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="hamlns:classification" name="cell-classification" minOccurs="0" maxOccurs="1"/>
            <xs:element type="hamlns:cdc-score" name="cdc-score" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:double" name="mfi-threshold" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:double" name="ratio-threshold" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="classification-entity" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="interpretation-reason" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <!-- TARGET-BEAD-OBSERVATION -->
    <xs:complexType name="target-bead-observation">
        <xs:annotation><xs:documentation>
            A single bead within e.g. a solid phase panel.
            The bead may have a specificity, which may be an allele name or a serological specificity.
            The target specificity and the role of the bead (target vs. control) is to be provided within the
            bead-info structure.

            Elements:
            ----------
            - bead-info: Structure containing details on the specificity and identifiers of an individual bead
            - bead-raw-data: Structure containing measured MFI or raw data as measured in the assay.
            - adjusted-data: Structure containing converted MFIs, formulas used,
                and computation methodology of bead-specific adjusted data.
            - bead-interpretation: Interpretation and results on single bead result
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element type="hamlns:bead-info" name="bead-info" minOccurs="1" maxOccurs="1" />
            <xs:element type="hamlns:bead-raw-data" name="bead-raw-data" minOccurs="0" maxOccurs="1" />
            <xs:element type="hamlns:adjusted-data" name="bead-adjusted-data" minOccurs="0" maxOccurs="unbounded" />
            <xs:element type="hamlns:bead-interpretation" name="bead-interpretation" minOccurs="0" maxOccurs="unbounded"/>
        </xs:all>
    </xs:complexType>

    <!-- TARGET-CELL-OBSERVATION -->
    <xs:complexType name="target-cell-observation">
        <xs:annotation><xs:documentation>
            A single cell observation within an e.g. Flow Crossmatch panel.
            The cell may have a specificity, which may be an allele name or a serological specificity.
            The target specificity and the role of the cell (target vs. control) is to be provided within the
            cell-info structure.

            Elements:
            ----------
            - cell-info: Structure containing details on the specificity and identifiers of an individual cell
            - cell-raw-data: Structure containing measured MFI or raw data as measured in the assay.
            - cell-adjusted-data: Structure containing converted MFIs, formulas used,
                and computation methodology of cell-specific adjusted data.
            - cell-interpretation: Interpretation data on single cell result
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element type="hamlns:cell-info" name="cell-info" minOccurs="1" maxOccurs="1" />
            <xs:element type="hamlns:cell-raw-data" name="cell-raw-data" minOccurs="0" maxOccurs="1" />
            <xs:element type="hamlns:adjusted-data" name="cell-adjusted-data" minOccurs="0" maxOccurs="unbounded" />
            <xs:element type="hamlns:cell-interpretation" name="cell-interpretation" minOccurs="0" maxOccurs="unbounded" />
        </xs:all>
    </xs:complexType>

    <!-- ASSAY-INTERPRETATION -->
    <xs:complexType name="assay-interpretation" >
        <xs:annotation><xs:documentation>
            An Interpretation is where we put the results of an entire assay.
            This includes which antigens/specificities are determined to be positive,
            negative or questionable based on the adjusted MFI scores of target bead
            observations.

            Elements:
            ------------
            - interpreter-id: A reference to the id of the results interpreter who performed this assay-interpretation
            - interpretation-context: A short summary of the reason for performing the interpretation.
                For example, "Clinical Interpretation" or "Kidney Transplantation"
            - interpretation-context-comment: Further commentary on clinical interpretation of the assay.
                Ex. "In the context of bone marrow transfusion we have identified these unacceptable
                specificities"
            - positive-specificities: PL String of positive antibody reactivity
            - questionable-specificities: PL String of questionable antibody reactivity
            - negative-specificities: PL String of negative antibody reactivity
            - reject-assay: Boolean if the assay was rejected or not.
            - reject-reason: Freeform Text describing why this assay result was rejected, and which entity made
                the determination to reject the assay
            - failure-code: An Integer value specifying an assay failure.
        </xs:documentation></xs:annotation>
        <xs:all>
            <xs:element name="interpreter-id" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="interpretation-context" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="interpretation-context-comment" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="specificities" type="hamlns:specificities" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="reject-assay" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
            <xs:element name="reject-reason" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="failure-code" type="xs:integer" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>
</xs:schema>